# Use an official Python runtime as a parent image
FROM python:3.8

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Run example.py when the container launches
CMD ["python", "./example.py"]


#TODO: from web3 import Web3
#import json
#import time
#import datetime
#import requests
#requirements.txt pip install req.....